.\" Man page for Lab 3
.\" Colin McCahill-Fall 2017

.TH lab3_man 1 "03 October 2017" "CSCI 241" "Oberlin College"

.SH NAME
.B lab3_man
\- my first man page

.SH SYNOPSIS
.B lab3_man
[ -o outputfile ]
<pig> <unpig> 

.SH DESCRIPTION 
Pig translates all words in the input to pig latin for input you give it phrases in English on the command line. Unpig translates the input to English.

.SH AUTHOR
Colin McCahill (Fall 2017)

.SH BUGS
At the moment the punctuation removal only removes punctuation at the end of words. (ran out of time to implement a different solution). It works well enough for the instructions of the lab but not for extreme cases. 
