.\" Man page for sort.c
.\" Colin McCahill - Fall 2017

.TH sort.c "26 October 2017" "CSCI 241" "Oberlin College"

.SH NAME
.B sort.1
-\ man page for sort.c

.SH SYNOPSIS
.B sort.1 
[ -o outputfile ]
<sort.c>

.SH DESCRIPTION
This program sorts lines in a text file. The default is to sort by alphabetical order. 

.SH OPTIONS
.IP "-n flag"
Sort in numerical order by the numbers at the beginning of line

.IP "-f flag"
Sort in alphabetical order regardless of capitalization

.IP "-r flag"
Sort any of the options in reverse order

.SH AUTHOR
Colin McCahill (Fall 2017)

.SH BUGS
None. 
